all: buffer3consDirectResume buffer3consDirectResumeResolved

clean:
	rm -f buffer3consDirectResume
	rm -f buffer3consDirectResumeResolved

buffer3consDirectResume: buffer3consDirectResume.cpp
	g++ buffer3consDirectResume.cpp -lpthread -o buffer3consDirectResume

buffer3consDirectResumeResolved: buffer3consDirectResumeResolved.cpp
	g++ buffer3consDirectResumeResolved.cpp -lpthread -o buffer3consDirectResumeResolved
